#!/usr/bin/env python3

# Unix-namer: A Unix naming convention standardizer written in python 3.
# https://github.com/zpiatt/unix-namer
#
# Copyright (C) 2023 Zac Piatt
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

VERSION = 'version: 0.8.2-beta - July 10, 2023'

import os, sys, hashlib, argparse, re

def get_file_hash(filepath):
    hasher = hashlib.sha256()
    with open(filepath, 'rb') as file:
        while (chunk := file.read(4096)):
            hasher.update(chunk)
    return hasher.hexdigest()

def unix_namer(directory, recursive, lowercase, field_separator, in_place_edit):
    if not os.path.isdir(directory):
        sys.exit(f"unix-namer: {directory}: Not a directory")

    equal, different, rename = [], [], []
    for root, dirs, files in os.walk(directory, topdown=False):
        if not recursive and root != directory:
            continue

        for filename in files + dirs:
            old_filepath = os.path.join(root, filename)
            if lowercase:
                filename = filename.lower()

            special_chars = "'!$^&*()[]|;~`<>{}()%"
            remove_special = str.maketrans(special_chars, len(special_chars) * ' ')

            temp_filename = filename.translate(remove_special).replace(' ', field_separator)
            new_filename = re.sub(fr'{field_separator}+', field_separator, temp_filename.rstrip(field_separator))

            new_filepath = os.path.join(root, new_filename)

            if os.path.exists(new_filepath) and os.path.abspath(old_filepath) != os.path.abspath(new_filepath):
                if os.path.isfile(old_filepath) and get_file_hash(old_filepath) == get_file_hash(new_filepath):
                    if in_place_edit:
                        os.remove(old_filepath)
                    else:
                        equal.append(f"{old_filepath} == {new_filepath}")
                else:
                    different.append(f"{old_filepath} != {new_filepath}")
            else:
                if old_filepath != new_filepath:
                    if in_place_edit:
                        os.rename(old_filepath, new_filepath)
                    else:
                        rename.append(f"{old_filepath} -> {new_filepath}")
    return equal, different, rename

def main():
    parser = argparse.ArgumentParser(usage='unix-namer [OPTION]... [DIR]...',
                                    description='Convert file & directory names to a Unix-friendly naming convention.',
                                    epilog=f'%(prog)s {VERSION}')
    parser.add_argument('directory', type=str, help='Target DIR')
    parser.add_argument('-r', '--recursive', action='store_true', help='Apply naming convention recursively.')
    parser.add_argument('-l', '--lowercase', action='store_true', help='Convert all names to lowercase.')
    parser.add_argument('-f', '--field-separator', metavar='', type=str, default='_', help='Specify field separator. Defaults to underscore.')
    parser.add_argument('-i', '--in-place-edit', action='store_true', help='In place edit. If naming conflicts occur, and file contents match, one file will be removed.')
    parser.add_argument('-v', '--version', action='version', version=f'%(prog)s {VERSION}')

    args = parser.parse_args()

    equal, different, rename = unix_namer(args.directory, args.recursive, args.lowercase, args.field_separator, args.in_place_edit)
    
    if rename:
        print("Files to be renamed:")
        print("\n".join(rename))
    if different:
        print("Naming conflicts: file contents do NOT match")
        print("\n".join(different))
    if equal:
        print("Naming conflicts: file contents match")
        print("\n".join(equal))

if __name__ == "__main__":
    main()